### PR TITLE
Use releval and conceal  for tray icon agains show and hide

### PR DESCRIPTION
**Pull request by alexkutsan**
I also don't like the place where gnome 3 moved legacy tray.
But this extension just removes tray and able to call it by shortcut. I don't think that it is required to completely remove tray because sometimes I need to open it with mouse. SO i prefer to reveal and conceal it by shortcut

### CODE REVIEW

**Comment by jonnylamb** [comment]
Thanks for your patch. I wrote the extension to suit my whims and I prefer not to have the tray icon present at all. Feel free to fork and start your own extension.

(The extension is _already_ quite hacky and brittle, but accessing `_revealHandle` feels even more so!)

**Comment by alexkutsan** [comment]
@jonnylamb can you advise place where can I read some documentation about Gnome3 js scripting? because all that I was did i found with gnome3-console.

**Comment by redianthus** [comment]
@alexkutsan, finding good documentation on this topic is hard. I'm afraid the best way to go would be learning by reading code from existing extensions.

**Comment by GuillaumeHM** [comment]
@jonnylamb Can this patch be integrated under a config option ?
Personally I would like another related config option : the legacyTray always conceal when hit the shortcut to avoid having two action to do the first time (hit shortcut and put mouse to the corner) and to make it completely disappear when hit shortcut again. It seems to be quite easy, isn't it ?

**Comment by alexkutsan** [comment]
@zapashcanon OK, but may be I at least can read sources of code that uses my extensions. To understand interfaces of objects that I need to use. Or how can I debug my code? At least with prints.

**Comment by redianthus** [comment]
```js
log("debug message blablabla");
```

No ? Not sure what you want to achieve.

**Pull request closed without merging**
